import Foundation

extension KSBindingsGenerator {
    /// Renders discovered commands and Codable types into a TypeScript module.
    /// Output includes a minimal invoke shim so generated bindings are standalone.
    static func render(commands: [Command], types: [TypeDecl], module: String) -> String {
        var out = ""
        out += "// AUTO-GENERATED by `kalsae generate bindings`. Do not edit.\n"
        out += "// Module: \(module)\n\n"

        // Keep this tiny shim in generated files so consumers can call commands
        // without importing additional runtime wrappers.
        out += """
            type InvokeFn = (cmd: string, args?: unknown) => Promise<unknown>;
            function _invoke(): InvokeFn {
            const w = (globalThis as any).__KS_;
            if (!w || typeof w.invoke !== 'function') {
            throw new Error('Kalsae runtime not available: window.__KS_.invoke missing');
            }
            return w.invoke as InvokeFn;
            }


            """

        renderTypes(types, into: &out)
        renderCommands(commands, into: &out)
        return out
    }

    // MARK: - Types
    private static func renderTypes(_ types: [TypeDecl], into out: inout String) {
        for t in types {
            switch t.kind {
            case .structType:
                renderStruct(t, into: &out)
            case .enumType:
                renderEnum(t, into: &out)
            }
        }
    }

    private static func renderStruct(_ t: TypeDecl, into out: inout String) {
        out += "export interface \(t.name) {\n"
        for f in t.fields {
            let isOpt = f.typeText.hasSuffix("?")
            let mapped = mapType(f.typeText)
            out += "  \(f.name)\(isOpt ? "?" : ""): \(mapped);\n"
        }
        out += "}\n\n"
    }

    private static func renderEnum(_ t: TypeDecl, into out: inout String) {
        if let raw = t.rawType, raw == "String" {
            let union = t.cases.map { "\"\($0.name)\"" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union);\n\n"
        } else if let raw = t.rawType, raw == "Int" {
            let union = t.cases.enumerated().map { "\($0.offset)" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union); /* int rawValues */\n\n"
        } else {
            // Discriminated union using `kind` for tagged enum variants.
            let parts: [String] = t.cases.map { c in
                if c.associated.isEmpty {
                    return "{ kind: \"\(c.name)\" }"
                }
                let fields = c.associated.map { f in
                    "\(f.name): \(mapType(f.typeText))"
                }.joined(separator: "; ")
                return "{ kind: \"\(c.name)\"; \(fields) }"
            }
            out += "export type \(t.name) =\n  | \(parts.joined(separator: "\n  | "));\n\n"
        }
    }

    // MARK: - Commands

    private static func renderCommands(_ commands: [Command], into out: inout String) {
        out += "export const App = {\n"
        for c in commands {
            renderCommand(c, into: &out)
        }
        out += "};\n"
    }

    private static func renderCommand(_ c: Command, into out: inout String) {
        let (inputType, inputArg) = renderParams(c.params)
        let ret = c.returnType.map(mapType) ?? "void"
        out += "  \(c.funcName)(\(inputType)): Promise<\(ret)> {\n"
        if c.params.isEmpty {
            out += "    return _invoke()(\"\(c.commandName)\") as Promise<\(ret)>;\n"
        } else {
            out += "    return _invoke()(\"\(c.commandName)\", \(inputArg)) as Promise<\(ret)>;\n"
        }
        out += "  },\n"
    }

    /// Returns a TS parameter declaration plus the JS argument expression
    /// forwarded to `_invoke()`.
    private static func renderParams(_ params: [Param]) -> (decl: String, arg: String) {
        if params.isEmpty {
            return ("", "")
        }
        if params.count == 1 {
            let p = params[0]
            let isOpt = p.typeText.hasSuffix("?")
            return (
                "\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))",
                "{ \(p.label) }"
            )
        }
        let entries = params.map { p -> String in
            let isOpt = p.typeText.hasSuffix("?")
            return "\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))"
        }
        return ("args: { \(entries.joined(separator: "; ")) }", "args")
    }
}
