import Foundation

extension KSBindingsGenerator {
    /// 수집된 명령과 Codable 타입을 단일 TypeScript 모듈 문자열로
    /// 렌더링한다. 출력에 작은 invoke shim이 포함되어
    /// 생성된 파일이 자체 완결된다.
    static func render(commands: [Command], types: [TypeDecl], module: String) -> String {
        var out = ""
        out += "// AUTO-GENERATED by `kalsae generate bindings`. Do not edit.\n"
        out += "// Module: \(module)\n\n"

        // 생성된 파일을 모듈로 제공할 때도 자립적으로 쓰일 수 있도록
        // 아주 작은 invoke 스텁을 포함시킨다.
        out += """
        type InvokeFn = (cmd: string, args?: unknown) => Promise<unknown>;
        function _invoke(): InvokeFn {
          const w = (globalThis as any).__KS_;
          if (!w || typeof w.invoke !== 'function') {
            throw new Error('Kalsae runtime not available: window.__KS_.invoke missing');
          }
          return w.invoke as InvokeFn;
        }


        """

        renderTypes(types, into: &out)
        renderCommands(commands, into: &out)
        return out
    }

    // MARK: - 타입

    private static func renderTypes(_ types: [TypeDecl], into out: inout String) {
        for t in types {
            switch t.kind {
            case .structType:
                renderStruct(t, into: &out)
            case .enumType:
                renderEnum(t, into: &out)
            }
        }
    }

    private static func renderStruct(_ t: TypeDecl, into out: inout String) {
        out += "export interface \(t.name) {\n"
        for f in t.fields {
            let isOpt = f.typeText.hasSuffix("?")
            let mapped = mapType(f.typeText)
            out += "  \(f.name)\(isOpt ? "?" : ""): \(mapped);\n"
        }
        out += "}\n\n"
    }

    private static func renderEnum(_ t: TypeDecl, into out: inout String) {
        if let raw = t.rawType, raw == "String" {
            let union = t.cases.map { "\"\($0.name)\"" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union);\n\n"
        } else if let raw = t.rawType, raw == "Int" {
            let union = t.cases.enumerated().map { "\($0.offset)" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union); /* int rawValues */\n\n"
        } else {
            // `kind` 태그를 사용하는 분별 유니온.
            let parts: [String] = t.cases.map { c in
                if c.associated.isEmpty {
                    return "{ kind: \"\(c.name)\" }"
                }
                let fields = c.associated.map { f in
                    "\(f.name): \(mapType(f.typeText))"
                }.joined(separator: "; ")
                return "{ kind: \"\(c.name)\"; \(fields) }"
            }
            out += "export type \(t.name) =\n  | \(parts.joined(separator: "\n  | "));\n\n"
        }
    }

    // MARK: - 명령

    private static func renderCommands(_ commands: [Command], into out: inout String) {
        out += "export const App = {\n"
        for c in commands {
            renderCommand(c, into: &out)
        }
        out += "};\n"
    }

    private static func renderCommand(_ c: Command, into out: inout String) {
        let (inputType, inputArg) = renderParams(c.params)
        let ret = c.returnType.map(mapType) ?? "void"
        out += "  \(c.funcName)(\(inputType)): Promise<\(ret)> {\n"
        if c.params.isEmpty {
            out += "    return _invoke()(\"\(c.commandName)\") as Promise<\(ret)>;\n"
        } else {
            out += "    return _invoke()(\"\(c.commandName)\", \(inputArg)) as Promise<\(ret)>;\n"
        }
        out += "  },\n"
    }

    /// TS 매개변수 선언 텍스트와 `_invoke()`에 전달할
    /// JS 인수 표현식을 반환한다.
    private static func renderParams(_ params: [Param]) -> (decl: String, arg: String) {
        if params.isEmpty {
            return ("", "")
        }
        if params.count == 1 {
            let p = params[0]
            let isOpt = p.typeText.hasSuffix("?")
            return ("\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))",
                    "{ \(p.label) }")
        }
        let entries = params.map { p -> String in
            let isOpt = p.typeText.hasSuffix("?")
            return "\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))"
        }
        return ("args: { \(entries.joined(separator: "; ")) }", "args")
    }
}
