import Foundation

extension KSBindingsGenerator {
    /// 발견된 커맨드 및 Codable 타입을 TypeScript 모듈로 렌더링한다.
    /// 출력에는 최소한의 invoke shim이 포함되어 생성된 바인딩이 독립적으로 동작 가능하다.
    static func render(commands: [Command], types: [TypeDecl], module: String) -> String {
        var out = ""
        out += "// AUTO-GENERATED by `kalsae generate bindings`. Do not edit.\n"
        out += "// Module: \(module)\n\n"

        // 제네레이티드 파일에 이 작은 shim을 포함시켜, 소비자가 별도의 런타임
        // 래퍼를 임포트하지 않고도 커맨드를 호출할 수 있게 한다.
        out += """
            type InvokeFn = (cmd: string, args?: unknown) => Promise<unknown>;
            function _invoke(): InvokeFn {
            const w = (globalThis as any).__KS_;
            if (!w || typeof w.invoke !== 'function') {
            throw new Error('Kalsae runtime not available: window.__KS_.invoke missing');
            }
            return w.invoke as InvokeFn;
            }


            """

        renderTypes(types, into: &out)
        renderCommands(commands, into: &out)
        return out
    }

    // MARK: - Types
    private static func renderTypes(_ types: [TypeDecl], into out: inout String) {
        for t in types {
            switch t.kind {
            case .structType:
                renderStruct(t, into: &out)
            case .enumType:
                renderEnum(t, into: &out)
            }
        }
    }

    private static func renderStruct(_ t: TypeDecl, into out: inout String) {
        out += "export interface \(t.name) {\n"
        for f in t.fields {
            let isOpt = f.typeText.hasSuffix("?")
            let mapped = mapType(f.typeText)
            out += "  \(f.name)\(isOpt ? "?" : ""): \(mapped);\n"
        }
        out += "}\n\n"
    }

    private static func renderEnum(_ t: TypeDecl, into out: inout String) {
        if let raw = t.rawType, raw == "String" {
            let union = t.cases.map { "\"\($0.name)\"" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union);\n\n"
        } else if let raw = t.rawType, raw == "Int" {
            let union = t.cases.enumerated().map { "\($0.offset)" }.joined(separator: " | ")
            out += "export type \(t.name) = \(union); /* int rawValues */\n\n"
        } else {
            // kind를 사용한 판별적 유니온(discriminated union) — tagged enum 변형.
            let parts: [String] = t.cases.map { c in
                if c.associated.isEmpty {
                    return "{ kind: \"\(c.name)\" }"
                }
                let fields = c.associated.map { f in
                    "\(f.name): \(mapType(f.typeText))"
                }.joined(separator: "; ")
                return "{ kind: \"\(c.name)\"; \(fields) }"
            }
            out += "export type \(t.name) =\n  | \(parts.joined(separator: "\n  | "));\n\n"
        }
    }

    // MARK: - Commands

    private static func renderCommands(_ commands: [Command], into out: inout String) {
        out += "export const App = {\n"
        for c in commands {
            renderCommand(c, into: &out)
        }
        out += "};\n"
    }

    private static func renderCommand(_ c: Command, into out: inout String) {
        let (inputType, inputArg) = renderParams(c.params)
        let ret = c.returnType.map(mapType) ?? "void"
        if let perm = c.permission {
            out += "  /** @permission \(perm) */\n"
        }
        out += "  \(c.funcName)(\(inputType)): Promise<\(ret)> {\n"
        if c.params.isEmpty {
            out += "    return _invoke()(\"\(c.commandName)\") as Promise<\(ret)>;\n"
        } else {
            out += "    return _invoke()(\"\(c.commandName)\", \(inputArg)) as Promise<\(ret)>;\n"
        }
        out += "  },\n"
    }

    /// TS 파라미터 선언과 `_invoke()`로 전달할 JS 인자 표현식을 함께 반환한다.
    private static func renderParams(_ params: [Param]) -> (decl: String, arg: String) {
        if params.isEmpty {
            return ("", "")
        }
        if params.count == 1 {
            let p = params[0]
            let isOpt = p.typeText.hasSuffix("?")
            return (
                "\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))",
                "{ \(p.label) }"
            )
        }
        let entries = params.map { p -> String in
            let isOpt = p.typeText.hasSuffix("?")
            return "\(p.label)\(isOpt ? "?" : ""): \(mapType(p.typeText))"
        }
        return ("args: { \(entries.joined(separator: "; ")) }", "args")
    }
}
