/// NSIS 인스톨러 스크립트(.nsi) 렌더러.
///
/// `KSPackager.run()` 산출 디렉터리(`<App>.exe`, `Kalsae.json`, `Resources/`,
/// `kalsae.runtime.json`, 옵션 `*.ico`, evergreen bootstrapper)를 시작 메뉴 +
/// 데스크톱 바로가기 + uninstaller가 있는 인스톨러로 묶는다.
///
/// 이 모듈은 NSIS를 호출하지 않는다 — 순수 문자열 렌더링이다. 실제 컴파일은
/// `KSPackager.runNSIS(_:)`가 `makensis`를 통해 수행한다.
public import Foundation

public enum KSNSISTemplate {
    public struct Options: Sendable {
        public var appName: String
        public var version: String
        public var identifier: String
        public var publisher: String?
        public var architecture: KSPackager.Architecture
        /// 인스톨러가 묶을 파일들이 있는 디렉터리 (`KSPackager.run()` 출력).
        public var sourceDir: URL
        /// 산출 .exe 인스톨러 파일명. 비우면 `<appName>-<version>-Setup.exe`.
        public var outputFileName: String?
        /// 인스톨러가 사용할 .ico (없으면 NSIS 기본).
        public var iconPath: URL?
        /// `MicrosoftEdgeWebview2Setup.exe` 가 sourceDir에 있으면 `--silent`로
        /// 부트스트랩한다. 파일명만 받고 경로는 sourceDir 기준.
        public var webView2BootstrapperFileName: String?

        public init(
            appName: String,
            version: String,
            identifier: String,
            publisher: String? = nil,
            architecture: KSPackager.Architecture,
            sourceDir: URL,
            outputFileName: String? = nil,
            iconPath: URL? = nil,
            webView2BootstrapperFileName: String? = nil
        ) {
            self.appName = appName
            self.version = version
            self.identifier = identifier
            self.publisher = publisher
            self.architecture = architecture
            self.sourceDir = sourceDir
            self.outputFileName = outputFileName
            self.iconPath = iconPath
            self.webView2BootstrapperFileName = webView2BootstrapperFileName
        }
    }

    /// 주어진 옵션으로 .nsi 스크립트 본문을 렌더링한다.
    public static func render(_ opts: Options) -> String {
        let installDir = "$PROGRAMFILES64\\\(escape(opts.appName))"
        let exeName = "\(opts.appName).exe"
        let outputName =
            opts.outputFileName
            ?? "\(opts.appName)-\(opts.version)-\(opts.architecture.rawValue)-Setup.exe"
        let publisher = opts.publisher ?? opts.identifier
        let regKey = "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\\(opts.identifier)"

        var lines: [String] = []
        lines.append("; Auto-generated by Kalsae CLI — do not edit by hand.")
        lines.append("; Re-run `kalsae build --nsis` to regenerate.")
        lines.append("")
        lines.append("Unicode true")
        lines.append("SetCompressor /SOLID lzma")
        lines.append("")
        lines.append("!define APP_NAME \"\(escape(opts.appName))\"")
        lines.append("!define APP_VERSION \"\(escape(opts.version))\"")
        lines.append("!define APP_IDENTIFIER \"\(escape(opts.identifier))\"")
        lines.append("!define APP_PUBLISHER \"\(escape(publisher))\"")
        lines.append("!define APP_EXE \"\(escape(exeName))\"")
        lines.append("")
        lines.append("Name \"${APP_NAME}\"")
        lines.append("OutFile \"\(escape(outputName))\"")
        lines.append("InstallDir \"\(installDir)\"")
        lines.append("InstallDirRegKey HKLM \"\(regKey)\" \"InstallLocation\"")
        lines.append("RequestExecutionLevel admin")
        if opts.architecture == .arm64 || opts.architecture == .x64 {
            lines.append("; 64-bit only — refuse to install on 32-bit hosts.")
        }
        lines.append("")
        if let icon = opts.iconPath {
            lines.append("Icon \"\(escape(icon.path))\"")
            lines.append("UninstallIcon \"\(escape(icon.path))\"")
        }
        lines.append("")
        lines.append("; ---- Install ----")
        lines.append("Section \"Install\"")
        lines.append("  SetOutPath \"$INSTDIR\"")
        lines.append("  ; Bundle entire packaged tree (ignore the bootstrapper — handled below).")
        let bootstrap = opts.webView2BootstrapperFileName ?? ""
        if bootstrap.isEmpty {
            lines.append("  File /r \"\(escape(opts.sourceDir.path))\\*.*\"")
        } else {
            lines.append("  File /r /x \"\(escape(bootstrap))\" \"\(escape(opts.sourceDir.path))\\*.*\"")
        }
        lines.append("")
        lines.append("  CreateDirectory \"$SMPROGRAMS\\${APP_NAME}\"")
        lines.append(
            "  CreateShortcut \"$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk\" \"$INSTDIR\\${APP_EXE}\"")
        lines.append("  CreateShortcut \"$DESKTOP\\${APP_NAME}.lnk\" \"$INSTDIR\\${APP_EXE}\"")
        lines.append("")
        lines.append("  WriteUninstaller \"$INSTDIR\\Uninstall.exe\"")
        lines.append("  WriteRegStr HKLM \"\(regKey)\" \"DisplayName\" \"${APP_NAME}\"")
        lines.append("  WriteRegStr HKLM \"\(regKey)\" \"DisplayVersion\" \"${APP_VERSION}\"")
        lines.append("  WriteRegStr HKLM \"\(regKey)\" \"Publisher\" \"${APP_PUBLISHER}\"")
        lines.append("  WriteRegStr HKLM \"\(regKey)\" \"InstallLocation\" \"$INSTDIR\"")
        lines.append("  WriteRegStr HKLM \"\(regKey)\" \"UninstallString\" \"$INSTDIR\\Uninstall.exe\"")
        if !bootstrap.isEmpty {
            lines.append("")
            lines.append("  ; WebView2 Evergreen runtime bootstrap (silent, idempotent).")
            lines.append("  ; The bootstrapper is included in the source tree but excluded from File")
            lines.append("  ; above and run from a temp copy so it is not left behind on disk.")
            lines.append("  SetOutPath \"$PLUGINSDIR\"")
            lines.append("  File \"\(escape(opts.sourceDir.appendingPathComponent(bootstrap).path))\"")
            lines.append(
                "  ExecWait '\"$PLUGINSDIR\\\(escape(bootstrap))\" /silent /install' $0")
        }
        lines.append("SectionEnd")
        lines.append("")
        lines.append("; ---- Uninstall ----")
        lines.append("Section \"Uninstall\"")
        lines.append("  Delete \"$DESKTOP\\${APP_NAME}.lnk\"")
        lines.append("  Delete \"$SMPROGRAMS\\${APP_NAME}\\${APP_NAME}.lnk\"")
        lines.append("  RMDir \"$SMPROGRAMS\\${APP_NAME}\"")
        lines.append("  RMDir /r \"$INSTDIR\"")
        lines.append("  DeleteRegKey HKLM \"\(regKey)\"")
        lines.append("SectionEnd")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// NSIS 인용에서 `\` 와 `"`만 escape 한다 (백슬래시는 NSIS에서 단일 리터럴
    /// 백슬래시이므로 경로용으로는 escape하지 않는다 — 이중 인용 안에서
    /// `\\`는 문자 그대로 두 백슬래시가 된다. 우리가 위에서 쓴 모든 경로는
    /// 이미 단일 `\` 를 가정하므로 그대로 둔다).
    private static func escape(_ s: String) -> String {
        s.replacingOccurrences(of: "\"", with: "$\\\"")
    }
}
