/// WiX v3 (`.wxs`) XML 렌더러.
///
/// `KSPackager.run()` 산출 디렉터리(`<App>.exe`, `kalsae.json`, `Resources/`,
/// `kalsae.runtime.json`, 옵션 `*.ico`)를 시작 메뉴 + 데스크톱 바로가기 + ARP
/// (Add/Remove Programs) 항목 + uninstall 흐름을 가진 MSI로 묶는다.
///
/// 이 모듈은 WiX를 호출하지 않는다 — 순수 문자열 렌더링이다. 실제 컴파일은
/// `KSPackager.runWiX(_:)`가 `candle.exe` + `light.exe`를 통해 수행한다.
///
/// 스키마는 WiX v3 (`http://schemas.microsoft.com/wix/2006/wi`). v4/v5는 별도 RFC.
public import Foundation
import KalsaeCore

public enum KSWiXTemplate {
    public struct Options: Sendable {
        public var appName: String
        public var version: String
        public var identifier: String
        public var publisher: String
        public var architecture: KSPackager.Architecture
        /// MSI가 묶을 파일들이 있는 디렉터리.
        public var sourceDir: URL
        /// MSI ProductCode — 매 빌드마다 새로 생성된다 (RFC 4122 §4.4 random).
        public var productCode: UUID
        /// MSI UpgradeCode — 절대 바뀌면 안 된다. 미지정 시
        /// `KSUUIDv5.wixUpgradeCode(productName:arch:)`로 결정론 생성.
        public var upgradeCode: UUID
        /// 인스톨러 아이콘 (.ico).
        public var iconPath: URL?
        /// 다운그레이드 허용 여부 (false면 `DowngradeErrorMessage` 강제).
        public var allowDowngrades: Bool
        /// 인스톨러 상단 배너 BMP (493×58).
        public var bannerPath: URL?
        /// 인스톨러 다이얼로그 배경 BMP (493×312).
        public var dialogImagePath: URL?
        /// WebView2 부트스트래퍼 실행 파일명 (sourceDir 기준). 비우면 미실행.
        public var webView2BootstrapperFileName: String?
        /// 부트스트래퍼 silent 실행 여부.
        public var webView2BootstrapperSilent: Bool
        /// 추가로 끼워 넣을 `<ComponentRef Id="..."/>` 목록.
        public var componentRefs: [String]
        /// 추가로 끼워 넣을 `<ComponentGroupRef Id="..."/>` 목록.
        public var componentGroupRefs: [String]
        /// 추가로 끼워 넣을 `<FeatureRef Id="..."/>` 목록.
        public var featureRefs: [String]
        /// 추가로 끼워 넣을 `<FeatureGroupRef Id="..."/>` 목록.
        public var featureGroupRefs: [String]
        /// 추가로 끼워 넣을 `<MergeRef Id="..."/>` 목록.
        public var mergeRefs: [String]

        public init(
            appName: String,
            version: String,
            identifier: String,
            publisher: String,
            architecture: KSPackager.Architecture,
            sourceDir: URL,
            productCode: UUID,
            upgradeCode: UUID,
            iconPath: URL? = nil,
            allowDowngrades: Bool = true,
            bannerPath: URL? = nil,
            dialogImagePath: URL? = nil,
            webView2BootstrapperFileName: String? = nil,
            webView2BootstrapperSilent: Bool = true,
            componentRefs: [String] = [],
            componentGroupRefs: [String] = [],
            featureRefs: [String] = [],
            featureGroupRefs: [String] = [],
            mergeRefs: [String] = []
        ) {
            self.appName = appName
            self.version = version
            self.identifier = identifier
            self.publisher = publisher
            self.architecture = architecture
            self.sourceDir = sourceDir
            self.productCode = productCode
            self.upgradeCode = upgradeCode
            self.iconPath = iconPath
            self.allowDowngrades = allowDowngrades
            self.bannerPath = bannerPath
            self.dialogImagePath = dialogImagePath
            self.webView2BootstrapperFileName = webView2BootstrapperFileName
            self.webView2BootstrapperSilent = webView2BootstrapperSilent
            self.componentRefs = componentRefs
            self.componentGroupRefs = componentGroupRefs
            self.featureRefs = featureRefs
            self.featureGroupRefs = featureGroupRefs
            self.mergeRefs = mergeRefs
        }
    }

    /// 주어진 옵션으로 `.wxs` 본문을 렌더링한다.
    public static func render(_ opts: Options) throws -> String {
        let archAttr: String = {
            switch opts.architecture {
            case .x64: return "x64"
            case .arm64: return "arm64"
            case .x86: return "x86"
            }
        }()
        let programFiles64 = opts.architecture == .x86 ? "ProgramFilesFolder" : "ProgramFiles64Folder"
        let exeName = "\(opts.appName).exe"
        let productVersion = normalizeVersion(opts.version)

        // 결정론적 컴포넌트 GUID를 생성할 namespace는 upgradeCode 자신.
        let componentNamespace = opts.upgradeCode

        var out = ""
        out.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        out.append("<!-- Auto-generated by Kalsae CLI — do not edit by hand. -->\n")
        out.append("<!-- Re-run `kalsae build --msi` to regenerate. -->\n")
        out.append("<Wix xmlns=\"http://schemas.microsoft.com/wix/2006/wi\">\n")
        out.append("  <Product Id=\"\(KSUUIDv5.format(opts.productCode))\"\n")
        out.append("           Name=\"\(esc(opts.appName))\"\n")
        out.append("           Language=\"1033\"\n")
        out.append("           Version=\"\(esc(productVersion))\"\n")
        out.append("           Manufacturer=\"\(esc(opts.publisher))\"\n")
        out.append("           UpgradeCode=\"\(KSUUIDv5.format(opts.upgradeCode))\">\n")
        out.append(
            "    <Package InstallerVersion=\"500\" Compressed=\"yes\" InstallScope=\"perMachine\""
                + " Manufacturer=\"\(esc(opts.publisher))\" Platform=\"\(archAttr)\" />\n")

        // MajorUpgrade — Tauri 동작 미러.
        if opts.allowDowngrades {
            out.append("    <MajorUpgrade AllowDowngrades=\"yes\" />\n")
        } else {
            out.append(
                "    <MajorUpgrade DowngradeErrorMessage=\""
                    + "A newer version of [ProductName] is already installed.\" />\n")
        }

        out.append("    <MediaTemplate EmbedCab=\"yes\" />\n")

        // ARP 아이콘.
        if opts.iconPath != nil {
            out.append("    <Icon Id=\"AppIcon.ico\" SourceFile=\"$(var.IconPath)\" />\n")
            out.append("    <Property Id=\"ARPPRODUCTICON\" Value=\"AppIcon.ico\" />\n")
        }

        // UI 배너/다이얼로그 변수.
        if opts.bannerPath != nil {
            out.append("    <WixVariable Id=\"WixUIBannerBmp\" Value=\"$(var.BannerPath)\" />\n")
        }
        if opts.dialogImagePath != nil {
            out.append("    <WixVariable Id=\"WixUIDialogBmp\" Value=\"$(var.DialogImagePath)\" />\n")
        }

        // 디렉터리 트리.
        out.append("    <Directory Id=\"TARGETDIR\" Name=\"SourceDir\">\n")
        out.append("      <Directory Id=\"\(programFiles64)\">\n")
        out.append("        <Directory Id=\"INSTALLFOLDER\" Name=\"\(esc(opts.appName))\">\n")
        // 파일 트리는 ComponentGroup로 분리해 INSTALLFOLDER에 참조한다.
        out.append("        </Directory>\n")
        out.append("      </Directory>\n")
        out.append("      <Directory Id=\"ProgramMenuFolder\">\n")
        out.append(
            "        <Directory Id=\"ApplicationProgramsFolder\" Name=\"\(esc(opts.appName))\" />\n")
        out.append("      </Directory>\n")
        out.append("      <Directory Id=\"DesktopFolder\" Name=\"Desktop\" />\n")
        out.append("    </Directory>\n")

        // 앱 파일 컴포넌트 그룹 (sourceDir BFS).
        out.append("    <ComponentGroup Id=\"AppFiles\" Directory=\"INSTALLFOLDER\">\n")
        try emitFileComponents(
            opts: opts,
            componentNamespace: componentNamespace,
            exeName: exeName,
            into: &out)
        out.append("    </ComponentGroup>\n")

        // 시작 메뉴 + 데스크톱 바로가기 컴포넌트.
        let startMenuComponentGuid =
            KSUUIDv5.v5(namespace: componentNamespace, name: "shortcut/start-menu")
        let desktopComponentGuid =
            KSUUIDv5.v5(namespace: componentNamespace, name: "shortcut/desktop")
        out.append(
            "    <DirectoryRef Id=\"ApplicationProgramsFolder\">\n"
                + "      <Component Id=\"AppStartMenuShortcut\" Guid=\"\(KSUUIDv5.format(startMenuComponentGuid))\">\n"
                + "        <Shortcut Id=\"AppStartMenuShortcut\" Name=\"\(esc(opts.appName))\""
                + " Description=\"\(esc(opts.appName))\""
                + " Target=\"[INSTALLFOLDER]\(esc(exeName))\""
                + " WorkingDirectory=\"INSTALLFOLDER\" />\n"
                + "        <RemoveFolder Id=\"RemoveAppProgramsFolder\" Directory=\"ApplicationProgramsFolder\" On=\"uninstall\" />\n"
                + "        <RegistryValue Root=\"HKCU\" Key=\"Software\\\(esc(opts.publisher))\\\(esc(opts.appName))\""
                + " Name=\"StartMenuShortcut\" Type=\"integer\" Value=\"1\" KeyPath=\"yes\" />\n"
                + "      </Component>\n"
                + "    </DirectoryRef>\n")
        out.append(
            "    <DirectoryRef Id=\"DesktopFolder\">\n"
                + "      <Component Id=\"AppDesktopShortcut\" Guid=\"\(KSUUIDv5.format(desktopComponentGuid))\">\n"
                + "        <Shortcut Id=\"AppDesktopShortcut\" Name=\"\(esc(opts.appName))\""
                + " Description=\"\(esc(opts.appName))\""
                + " Target=\"[INSTALLFOLDER]\(esc(exeName))\""
                + " WorkingDirectory=\"INSTALLFOLDER\" />\n"
                + "        <RegistryValue Root=\"HKCU\" Key=\"Software\\\(esc(opts.publisher))\\\(esc(opts.appName))\""
                + " Name=\"DesktopShortcut\" Type=\"integer\" Value=\"1\" KeyPath=\"yes\" />\n"
                + "      </Component>\n"
                + "    </DirectoryRef>\n")

        // WebView2 부트스트래퍼 CustomAction.
        if let boot = opts.webView2BootstrapperFileName, !boot.isEmpty {
            let silent = opts.webView2BootstrapperSilent ? " /silent /install" : " /install"
            out.append(
                "    <CustomAction Id=\"InstallWebView2\""
                    + " FileKey=\"WebView2BootstrapperFile\""
                    + " ExeCommand=\"\(esc(silent))\""
                    + " Execute=\"deferred\" Impersonate=\"no\" Return=\"ignore\" />\n")
            out.append("    <InstallExecuteSequence>\n")
            out.append(
                "      <Custom Action=\"InstallWebView2\" After=\"InstallFiles\">NOT Installed</Custom>\n")
            out.append("    </InstallExecuteSequence>\n")
            _ = boot
        }

        // 메인 Feature.
        out.append(
            "    <Feature Id=\"MainFeature\" Title=\"\(esc(opts.appName))\""
                + " Level=\"1\" ConfigurableDirectory=\"INSTALLFOLDER\">\n")
        out.append("      <ComponentGroupRef Id=\"AppFiles\" />\n")
        out.append("      <ComponentRef Id=\"AppStartMenuShortcut\" />\n")
        out.append("      <ComponentRef Id=\"AppDesktopShortcut\" />\n")
        for r in opts.componentRefs {
            out.append("      <ComponentRef Id=\"\(esc(r))\" />\n")
        }
        for r in opts.componentGroupRefs {
            out.append("      <ComponentGroupRef Id=\"\(esc(r))\" />\n")
        }
        for r in opts.featureRefs {
            out.append("      <FeatureRef Id=\"\(esc(r))\" />\n")
        }
        for r in opts.featureGroupRefs {
            out.append("      <FeatureGroupRef Id=\"\(esc(r))\" />\n")
        }
        for r in opts.mergeRefs {
            out.append("      <MergeRef Id=\"\(esc(r))\" />\n")
        }
        out.append("    </Feature>\n")

        // UI.
        out.append("    <UIRef Id=\"WixUI_InstallDir\" />\n")
        out.append(
            "    <Property Id=\"WIXUI_INSTALLDIR\" Value=\"INSTALLFOLDER\" />\n")

        out.append("  </Product>\n")
        out.append("</Wix>\n")
        return out
    }

    // MARK: - 내부

    /// sourceDir BFS — 각 파일을 별도 `<Component>` + `<File>`로 emit.
    /// 결정론적 컴포넌트 GUID = v5(namespace=upgradeCode, name=relativePath).
    private static func emitFileComponents(
        opts: Options,
        componentNamespace: UUID,
        exeName: String,
        into out: inout String
    ) throws {
        let fm = FileManager.default
        let bootstrapper = opts.webView2BootstrapperFileName ?? ""

        // 결정론 정렬을 위해 모든 파일을 수집 후 정렬.
        var files: [(absURL: URL, rel: String)] = []
        guard
            let enumerator = fm.enumerator(
                at: opts.sourceDir,
                includingPropertiesForKeys: [.isRegularFileKey],
                options: [.skipsHiddenFiles])
        else {
            throw ShellError.message(
                "WiX template: failed to enumerate sourceDir at \(opts.sourceDir.path)")
        }
        let basePath = opts.sourceDir.standardizedFileURL.path
        for case let item as URL in enumerator {
            let attrs = try item.resourceValues(forKeys: [.isRegularFileKey])
            guard attrs.isRegularFile == true else { continue }
            let abs = item.standardizedFileURL.path
            guard abs.hasPrefix(basePath) else { continue }
            var rel = String(abs.dropFirst(basePath.count))
            while rel.hasPrefix("/") || rel.hasPrefix("\\") { rel.removeFirst() }
            files.append((absURL: item, rel: rel))
        }
        files.sort { $0.rel.lowercased() < $1.rel.lowercased() }

        // INSTALLFOLDER 자체는 ComponentGroup의 Directory 속성에 이미 묶여 있다.
        // 하위 디렉터리는 `Subdirectory` 속성으로 표현 (WiX v3.6+).
        var compIndex = 0
        for entry in files {
            // bootstrapper는 항상 포함 (CustomAction이 이를 실행).
            let _ = bootstrapper
            let safeId = safeIdentifier(prefix: "c", index: compIndex, hint: entry.rel)
            let fileId = safeIdentifier(prefix: "f", index: compIndex, hint: entry.rel)
            let compGuid = KSUUIDv5.v5(namespace: componentNamespace, name: entry.rel)
            let dirComponents = entry.rel
                .replacingOccurrences(of: "\\", with: "/")
                .split(separator: "/")
                .dropLast()
                .map(String.init)
            let subdirAttr: String
            if dirComponents.isEmpty {
                subdirAttr = ""
            } else {
                subdirAttr = " Subdirectory=\"\(esc(dirComponents.joined(separator: "\\")))\""
            }
            let isBootstrapper =
                !bootstrapper.isEmpty
                && entry.rel.replacingOccurrences(of: "\\", with: "/")
                    == bootstrapper.replacingOccurrences(of: "\\", with: "/")
            let fileIdEffective = isBootstrapper ? "WebView2BootstrapperFile" : fileId
            out.append(
                "      <Component Id=\"\(safeId)\" Guid=\"\(KSUUIDv5.format(compGuid))\""
                    + "\(subdirAttr)>\n")
            out.append(
                "        <File Id=\"\(fileIdEffective)\" Source=\"\(esc(entry.absURL.path))\""
                    + " KeyPath=\"yes\"")
            if entry.rel.lowercased() == exeName.lowercased() {
                out.append(" />\n")
            } else {
                out.append(" />\n")
            }
            out.append("      </Component>\n")
            compIndex += 1
        }
    }

    /// `M.m.p[.b]` 형식으로 정규화. SemVer pre-release/build metadata는 제거.
    /// 0~65535 범위로 클램프.
    public static func normalizeVersion(_ s: String) -> String {
        // pre-release/build metadata 제거.
        var core = s
        if let plus = core.firstIndex(of: "+") { core.removeSubrange(plus...) }
        if let dash = core.firstIndex(of: "-") { core.removeSubrange(dash...) }
        let parts = core.split(separator: ".").map { String($0) }
        var nums: [Int] = []
        for p in parts {
            if let n = Int(p) { nums.append(max(0, min(65535, n))) }
        }
        while nums.count < 3 { nums.append(0) }
        if nums.count > 4 { nums = Array(nums.prefix(4)) }
        return nums.map(String.init).joined(separator: ".")
    }

    /// WiX Id 토큰으로 안전한 문자열을 만든다 — 영숫자/`.`/`_`만 허용.
    /// 동일 hint+index는 동일 결과 보장.
    public static func safeIdentifier(prefix: String, index: Int, hint: String) -> String {
        var sanitized = ""
        for ch in hint.unicodeScalars {
            if CharacterSet.alphanumerics.contains(ch) {
                sanitized.unicodeScalars.append(ch)
            } else if ch == "." || ch == "_" {
                sanitized.unicodeScalars.append(ch)
            } else {
                sanitized.append("_")
            }
        }
        // 너무 긴 hint는 끝부분만 사용.
        if sanitized.count > 40 {
            sanitized = String(sanitized.suffix(40))
        }
        return "\(prefix)\(index)_\(sanitized)"
    }

    /// XML attribute/text escape.
    private static func esc(_ s: String) -> String {
        var r = s
        r = r.replacingOccurrences(of: "&", with: "&amp;")
        r = r.replacingOccurrences(of: "\"", with: "&quot;")
        r = r.replacingOccurrences(of: "<", with: "&lt;")
        r = r.replacingOccurrences(of: ">", with: "&gt;")
        return r
    }
}
