import SwiftSyntax
import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import Testing

@testable import KalsaeMacrosPlugin

private let macros: [String: Macro.Type] = [
    "KSCommand": KSCommandMacro.self
]
@Suite("KSCommandMacro expansion")
struct KSCommandMacroTests {

    @Test("Simple sync non-throwing function with one param")
    func simpleSync() {
        assertMacroExpansion(
            """
            @KSCommand
            func greet(name: String) -> String {
            "Hello, \\(name)!"
            }
            """,
            expandedSource: """
                func greet(name: String) -> String {
                "Hello, \\(name)!"
                }

                /// Registers `greet` into `registry` under the name
                /// `"greet"`. Generated by `@KSCommand`.
                func _ksRegister_greet(into registry: KalsaeCore.KSCommandRegistry) async {
                await registry.register("greet") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                struct __Args: Swift.Decodable {
                let name: String
                }
                let args: __Args
                do {
                args = try Foundation.JSONDecoder().decode(__Args.self, from: data)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandDecodeFailed,
                message: String(describing: error)))
                }
                let __result = greet(name: args.name)
                do {
                let __payload = try Foundation.JSONEncoder().encode(__result)
                return .success(__payload)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandEncodeFailed,
                message: String(describing: error)))
                }
                }
                }
                """,
            macros: macros)
    }

    @Test("Custom registry name")
    func customName() {
        assertMacroExpansion(
            """
            @KSCommand("user.greet")
            func greet() -> String { "Hi" }
            """,
            expandedSource: """
                func greet() -> String { "Hi" }

                /// Registers `greet` into `registry` under the name
                /// `"user.greet"`. Generated by `@KSCommand`.
                func _ksRegister_greet(into registry: KalsaeCore.KSCommandRegistry) async {
                await registry.register("user.greet") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                struct __Args: Swift.Decodable {

                }
                let args = __Args()
                    _ = args
                    _ = data
                let __result = greet()
                do {
                let __payload = try Foundation.JSONEncoder().encode(__result)
                return .success(__payload)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandEncodeFailed,
                message: String(describing: error)))
                }
                }
                }
                """,
            macros: macros)
    }

    @Test("Async throwing function expands with try/await")
    func asyncThrowing() {
        assertMacroExpansion(
            """
            @KSCommand
            func work(x: Int) async throws -> Int { x * 2 }
            """,
            expandedSource: #"""
                func work(x: Int) async throws -> Int { x * 2 }

                /// Registers `work` into `registry` under the name
                /// `"work"`. Generated by `@KSCommand`.
                func _ksRegister_work(into registry: KalsaeCore.KSCommandRegistry) async {
                await registry.register("work") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                struct __Args: Swift.Decodable {
                let x: Int
                }
                let args: __Args
                do {
                args = try Foundation.JSONDecoder().decode(__Args.self, from: data)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandDecodeFailed,
                message: String(describing: error)))
                }
                let __result: Int
                do {
                __result = try await work(x: args.x)
                } catch let e as KalsaeCore.KSError {
                return .failure(e)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandExecutionFailed,
                message: String(describing: error)))
                }
                do {
                let __payload = try Foundation.JSONEncoder().encode(__result)
                return .success(__payload)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandEncodeFailed,
                message: String(describing: error)))
                }
                }
                }
                """#,
            macros: macros)
    }

    @Test("Void return produces empty JSON object")
    func voidReturn() {
        assertMacroExpansion(
            """
            @KSCommand
            func log(msg: String) {}
            """,
            expandedSource: #"""
                func log(msg: String) {}

                /// Registers `log` into `registry` under the name
                /// `"log"`. Generated by `@KSCommand`.
                func _ksRegister_log(into registry: KalsaeCore.KSCommandRegistry) async {
                await registry.register("log") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                struct __Args: Swift.Decodable {
                let msg: String
                }
                let args: __Args
                do {
                args = try Foundation.JSONDecoder().decode(__Args.self, from: data)
                } catch {
                return .failure(KalsaeCore.KSError(
                code: .commandDecodeFailed,
                message: String(describing: error)))
                }
                log(msg: args.msg)
                let __payload = Foundation.Data("{}".utf8)
                return .success(__payload)
                }
                }
                """#,
            macros: macros)
    }
}
