import SwiftSyntax
import SwiftSyntaxMacros
import SwiftSyntaxMacrosGenericTestSupport
import Testing

@testable import KalsaeMacrosPlugin

private let macros: [String: Macro.Type] = [
    "KSCommand": KSCommandMacro.self
]

@Suite("KSCommandMacro permission parameter")
struct KSCommandPermissionMacroTests {

    @Test("permission only emits setMetadata call")
    func permissionOnly() {
        expectMacroExpansion(
            #"""
            @KSCommand(permission: "fs:read")
            func readFile() -> String { "" }
            """#,
            expandedSource: #"""
                func readFile() -> String { "" }

                /// Argument payload for `readFile`. Generated by `@KSCommand`.
                struct __KSArgs_readFile: Swift.Decodable {
                }

                /// Registers `readFile` into `registry` under the name
                /// `"readFile"`. Generated by `@KSCommand`.
                func _ksRegister_readFile(into registry: KalsaeCore.KSCommandRegistry) async {
                    await registry.register("readFile") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                        let args = __KSArgs_readFile()
                                    _ = args
                                    _ = data
                        let __result = readFile()
                        do {
                            let __payload = try Foundation.JSONEncoder().encode(__result)
                            return .success(__payload)
                        } catch {
                            return .failure(KalsaeCore.KSError(
                                    code: .commandEncodeFailed,
                                    message: String(describing: error)))
                        }
                    }
                    await registry.setMetadata("readFile", permission: "fs:read")
                }
                """#,
            macros: macros)
    }

    @Test("name + permission combined")
    func nameAndPermission() {
        expectMacroExpansion(
            #"""
            @KSCommand("fs.read", permission: "fs:read")
            func readFile() -> String { "" }
            """#,
            expandedSource: #"""
                func readFile() -> String { "" }

                /// Argument payload for `readFile`. Generated by `@KSCommand`.
                struct __KSArgs_readFile: Swift.Decodable {
                }

                /// Registers `readFile` into `registry` under the name
                /// `"fs.read"`. Generated by `@KSCommand`.
                func _ksRegister_readFile(into registry: KalsaeCore.KSCommandRegistry) async {
                    await registry.register("fs.read") { @Sendable (data: Foundation.Data) async -> Swift.Result<Foundation.Data, KalsaeCore.KSError> in
                        let args = __KSArgs_readFile()
                                    _ = args
                                    _ = data
                        let __result = readFile()
                        do {
                            let __payload = try Foundation.JSONEncoder().encode(__result)
                            return .success(__payload)
                        } catch {
                            return .failure(KalsaeCore.KSError(
                                    code: .commandEncodeFailed,
                                    message: String(describing: error)))
                        }
                    }
                    await registry.setMetadata("fs.read", permission: "fs:read")
                }
                """#,
            macros: macros)
    }

    @Test("Empty permission string is rejected")
    func emptyPermission() {
        expectMacroExpansion(
            #"""
            @KSCommand(permission: "")
            func go() {}
            """#,
            expandedSource: """
                func go() {}
                """,
            diagnostics: [
                .init(
                    message: "@KSCommand `permission:` argument must not be an empty string.",
                    line: 1, column: 24)
            ],
            macros: macros)
    }

    @Test("Non-literal permission emits diagnostic")
    func nonLiteralPermission() {
        expectMacroExpansion(
            """
            @KSCommand(permission: 42)
            func go() {}
            """,
            expandedSource: """
                func go() {}
                """,
            diagnostics: [
                .init(
                    message:
                        "@KSCommand `permission:` argument requires a plain string literal (no interpolation).",
                    line: 1, column: 24)
            ],
            macros: macros)
    }

    @Test("Unknown argument label is rejected")
    func unknownLabel() {
        expectMacroExpansion(
            #"""
            @KSCommand(scope: "fs")
            func go() {}
            """#,
            expandedSource: """
                func go() {}
                """,
            diagnostics: [
                .init(
                    message:
                        "@KSCommand accepts only the unlabeled name argument and `permission:`; unknown argument labels are rejected.",
                    line: 1, column: 12)
            ],
            macros: macros)
    }
}
